# Generated by Django 5.1 on 2024-09-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0002_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="tax",
            name="stripe_tax_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
