# Generated by Django 5.1 on 2024-09-06 13:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="product",
            new_name="item",
        ),
    ]
