# Generated by Django 5.1 on 2024-09-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0002_tax"),
        ("orders", "0005_order_coupon_order_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="tax",
            field=models.ManyToManyField(
                blank=True, to="coupons.tax", verbose_name="Налог"
            ),
        ),
    ]
